### ISSUE TITLE
Phone Won't Boot

### ISSUE THREAD

**Issue by capt-meelo** [Magisk-Modules-Repo/NotchBarKiller#3]
I installed this on Xiaomi Mi A2 Lite and after a reboot, my phone won't boot now. It says "Can't load Android System. Your data may be corrupt."

**Comment by bin3811** [comment]
I am having the same issue, after I installed this module on my Xiaomi Redmi 6 Pro, the phone cannot boot. It  just stucks at the boot animation. Flashing Magisk uninstaller does not work.

**Comment by exolon** [comment]
Same here. OP6, OB9, phone stuck at boot animation.

**Comment by Masonjar13** [comment]
Wish I read this before I installed it. Is there anyway to get it booting without flashing a new ROM?

**Comment by bin3811** [comment]
> Wish I read this before I installed it. Is there anyway to get it booting without flashing a new ROM?

I had to flash the ROM again and and wipe data in TWRP to make the phone boot again, or it would stay in bootloop. I couldn't find another way to make it boot.

**Comment by exolon** [comment]
Yeah, unfortunately I didn't find a way to fix it. No amount of reflashing or trying to uninstall/wipe modules etc helped...

**Comment by Masonjar13** [comment]
This issue should be stated very clearly in the Magisk repo, or have the module removed from the repo entirely. I went ahead and wiped and flashed.

**Comment by MatChung** [comment]
I'm running this module on my OnePlus 6T and manage to fix the bootloop issue. (I had never think that Magisk module can cause bootloop before).

`/data/resource-cache/overlays.list`

it contains the overlay resources, forces system to load the files during boot.
```
/vendor/overlay/framework-res__auto_generated_rro.apk
/data/resource-cache/vendor@overlay@framework-res__auto_generated_rro.apk@idmap
```
If we disable/remove the module, it causes bootloop due to error:

`
W ziparchive: Unable to open '/vendor/overlay/framework-res__auto_generated_rro.apk': No such file or directory
`

So the solution is to delete this file manually (TRWP can help) after disable/removing the magisk module. No data wipe is required. Hope this can help.

**Comment by HazemDa1st** [comment]
Hey @MatChung I'm really thankful for you, your soulation works

**Comment by Kabi10** [comment]
> I'm running this module on my OnePlus 6T and manage to fix the bootloop issue. (I had never think that Magisk module can cause bootloop before).
> 
> `/data/resource-cache/overlays.list`
> 
> it contains the overlay resources, forces system to load the files during boot.
> 
> ```
> /vendor/overlay/framework-res__auto_generated_rro.apk
> /data/resource-cache/vendor@overlay@framework-res__auto_generated_rro.apk@idmap
> ```
> If we disable/remove the module, it causes bootloop due to error:
> 
> `W ziparchive: Unable to open '/vendor/overlay/framework-res__auto_generated_rro.apk': No such file or directory`
> 
> So the solution is to delete this file manually (TRWP can help) after disable/removing the magisk module. No data wipe is required. Hope this can help.

Omg, thankyou dude!, lifesaver!!! I made an account too just to say thanks. thanks alot!!!
